### ISSUE TITLE
update source mapping 

### ISSUE THREAD

**Issue by manageryzy** [RoyalAliceAcademyOfSciences/SimElectricity#13]
forge 1.12 is going to end it's life soon. be we still use snapshot mapping instead of stable mapping

**Comment by AuroraRAS** [comment]
The latest snapshot is recommended on the client, it will be compatible with most mods. If mod developers use the stable forge, maybe it compatible with more clients? I'm not sure.

**Comment by manageryzy** [comment]
in newer versions `EnumFacing.getFront` was renamed into `EnumFacing.byIndex` , `unlocalizedName` was rename into `translationKey` ...

these new names were still used in mcp_stable_60 for minecraft 1.15* 
we should upgrade our mcp for newer version support

**Comment by rikka0w0** [comment]
[mods.zip](https://github.com/RoyalAliceAcademyOfSciences/SimElectricity/files/4657136/mods.zip)
1.15.2 Test mod pack
