### ISSUE TITLE
build failed (gradle)

### ISSUE THREAD

**Issue by ptk2003** [RoyalAliceAcademyOfSciences/SimElectricity#16]
Hi.
Can't build the project, "Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0"
[console log.txt](https://github.com/RoyalAliceAcademyOfSciences/SimElectricity/files/6369920/console.log.txt)

**Comment by AuroraRAS** [comment]
Don't worry.
Can you provide earlier logs? like "git submodule init" and "git submodule update" parts.

**Comment by rikka0w0** [comment]
Seems like you forget to run `git submodule init` and `git submodule update`. Try to run these two commands before building the project. In addition, which branch are you using? The main branch may not be up-to-date, try the `1.16.4` branch. Contact me if the error presists.
